pretrains:
  sd_pretrains_folder: pretrains/SD/stable-diffusion-v1-5/
  lcm_pretrains_path: latent-consistency/lcm-lora-sdv1-5
  lcvideo_checkpoint_path: checkpoints/lcvideo_unet.pth

video:
  prompt: Horse grazing - seperated on green screen
  height: 256
  width: 256
  num_frames: 8
  num_inference_steps: 5
  guidance_scale: 1.
  video_fps: 8
  output_path: samples/test.gif