output_dir: checkpoints
output_name: unet_video.pth
device: cuda
lr_scheduler_name: cosine
enable_gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
mixed_precision: fp16
lr_warmup_steps: 10
gradient_accumulation_steps: 1
clip_grad_norm: 1.
batch_size: 1
num_epochs: 200
checkpoint_epochs: 20
load_checkpoint: False
checkpoint_path: checkpoints/unet_video.pth

optimizer:
  learning_rate: 1.e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.e-8
  adam_weight_decay: 1.e-4

data:
  csv_path: /home/skytim/data/webvid/results_2M_val.csv
  video_folder: /home/skytim/data/webvid/data/videos/
  height: 512
  width: 512
  num_frames: 4
  max_num_frames: 24
  frame_stride: 4
  dataloader_num_worker: 4

pretrains:
  sd_pretrains_folder: pretrains/SD/stable-diffusion-v1-5/
  lcm_pretrains_path: pretrains/LCM/lcm_lora_sd15.safetensors